theme: minima
title: Coding PanDad
author: jiunrenwang
email: jiunrenwang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A (not so) epic tale of a stay-at-home dad trying to go back to school and learn how to become a
  Front End developer.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jiunrenwang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
